"""Prognosis added

Revision ID: 070242d416cf
Revises: 7599a54a0f41
Create Date: 2024-10-24 07:31:15.823703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070242d416cf'
down_revision = '7599a54a0f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prognosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_', sa.String(length=1), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('one_year', sa.Float(), nullable=True),
    sa.Column('two_years', sa.Float(), nullable=True),
    sa.Column('perioperative_mortality', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prognosis')
    # ### end Alembic commands ###
