"""Removed date rule from birthdate

Revision ID: d7aa9f623d4c
Revises: 070242d416cf
Create Date: 2024-11-12 11:30:05.713416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7aa9f623d4c'
down_revision = '070242d416cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prognosis', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('birthDate',
               existing_type=sa.DATE(),
               type_=sa.String(length=45),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('birthDate',
               existing_type=sa.String(length=45),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('prognosis', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
